version: '3.9'

services:
  frontend:
    container_name: template-next14-init
    ports:
      - 80:3000
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "5"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile


