name: template-next14-init-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/ihartsykala/template-next14-init
  DOCKER_IMAGE_TAG: prod
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: ihartsykala
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io
          sudo usermod -aG docker $USER
          docker --version

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker container if exists
        run: docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }} || true

      - name: Build, tag, and push image to registry
        id: build-image
        run: |
          docker build -f Dockerfile -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }} .
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Set up SSH key and deploy to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 159.223.170.64 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Run deployment script
        run: |
          chmod +x deploy_script.sh
          ./deploy_script.sh ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE_TAG }}
