name: template-next14-init-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/ihartsykala/template-next14-init
  DOCKER_IMAGE_TAG: prod
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: ihartsykala

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: log in to gitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker container if exists
        run: docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }} || true

      - name: Build, tag, and push image to registry
        id: build-image
        run: |
          docker build -f Dockerfile -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }} .
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Set up SSH key and deploy to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 159.223.170.64 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          echo "SSH private key:"
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          
          echo "SSH private key2:"
          cat ~/.ssh/id_rsa
          

      - name: Pull Docker image from registry
        run: docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Run Docker container on the server
        run: |
          ssh -i ~/.ssh/id_rsa root@159.223.170.64 "/usr/bin/docker stop \$(/usr/bin/docker ps -aq) || true && /usr/bin/docker rm \$(/usr/bin/docker ps -aq) || true"
          ssh -i ~/.ssh/id_rsa root@159.223.170.64 "/usr/bin/docker run -d -p 80:3000 ghcr.io/ihartsykala/template-next14-init:prod"

#      - name: Deploy to server
#        run: |
#          ssh -i ~/.ssh/id_rsa root@159.223.170.64
