name: template-next14-init-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/ihartsykala/template-next14-init
  DOCKER_IMAGE_TAG: prod
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: ihartsykala

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: log in to gitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker container if exists
        run: docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }} || true

      - name: Build, tag, and push image to registry
        id: build-image
        run: |
          docker build -f Dockerfile -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }} .
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Set up SSH
        run: |
          mkdir -p $RUNNER_HOME/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDik4QGCYXzexP+ZF3IJxWwZ6y2EcQQPSN2oZX037Xnern3LiREqAFvKnJIMcfb9uRMX5USrrWXg46QfjMCSMjdiI/TnZ9hAE4T8Ah3UqtQ7uiWiTxCrebOTp0zivt3j+h6cYwQSGnIViljOEFBEtu70owbJBNqQv8vPZBme0EZIozSd9nIoDq7iM0hT6mdMxtAfsk78ROGuIr09ULUtOR4mUogyxNnh29TOHmq/MWw4zESiTHK/cOzcslVmvK5SMYVzoc43FxeUpuUI7lUGBunI04J22dZT6nML7Cfl/v1QV52JrE347dpAish7REtvIOs8KjkyeFlL0iKJH4Za99t ihartsykala@Ihars-MacBook-Pro.local" > $RUNNER_HOME/.ssh/id_rsa
          chmod 600 $RUNNER_HOME/.ssh/id_rsa
          ssh-keyscan 165.22.0.137 >> $RUNNER_HOME/.ssh/known_hosts

      - name: Update deployment on the server
        run: |
          ssh -i ~/.ssh/id_rsa root@165.22.0.137 "cd /var/www/html && docker system prune -f && docker-compose pull && docker-compose up -d"
      
